//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRPO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int Row_Id { get; set; }
        public int Plice_Id { get; set; }
        public int Status_Id { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Row Row { get; set; }
        public virtual Status Status { get; set; }
    }
}
